name: generator

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Update archive
        uses: linuxsuren/yaml-readme@v0.0.13
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'items/*.yaml'
          template: 'README.tpl'
          output: 'README.md'
          username: linuxsuren
          org: linuxsuren
          repo: open-source-events
          sortby: date
          groupby: year
